server:
  port: 8000
  read-timeout: 60
  write-timeout: 60
  run-mode: debug

mysql:
  url: "127.0.0.1:3306"
  username: root
  password: admin
  dbname: wechat

redis:
  addrs:
    - "127.0.0.1:6379"
  pwd:
  poolsize: 1000
  db: 1
  timeout: 1000
  expired-time: 3600