basePath: /apis/v1
definitions:
  models.User:
    properties:
      avatar_url:
        type: string
      city:
        type: string
      email:
        type: string
      gender:
        type: string
      id:
        type: integer
      nickname:
        type: string
      phone:
        type: string
      provincial:
        type: string
      register_time:
        type: integer
      uid:
        type: string
    type: object
host: 127.0.0.1:8000
info:
  contact:
    email: me@razeen.me
    name: Razeen
    url: https://razeen.me
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://razeen.me
  title: Swagger Example API
  version: "1.0"
paths:
  /phone_login:
    post:
      consumes:
      - application/json
      description: 测试手机号登录
      parameters:
      - description: 用户数据
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/models.User'
      responses:
        "200":
          description: '{"code": -1, "message": "添加失败"}'
          schema:
            type: string
      summary: 手机号登录
      tags:
      - 用户
swagger: "2.0"
